//
// API ENDPOINTS USER
//

// HÄMTA ALLA USERS // SKICKA INTE MED LÖSENORD // BARA ID, NAMN + EMAIL PÅ ALLA USERS
# 
GET http://localhost:3000/admins

###

# 
GET http://localhost:3000/information

###

###

// LOGGA IN USER
POST http://localhost:3000/admins/login
Content-Type: application/json

{
  "username": "admin",
  "password": "hemligt"
}

###

// LOGGA IN USER
POST http://localhost:3000/addOrder
Content-Type: application/json

{
  "firstName": "jonas",
  "lastName": "bergman",
  "phone": "0171544543",
  "email": "xxx@test.net",
  "address": "Tebyvegen 9",
  "city": "Uppsala",
  "postCode": "74565",
  "totalCost": "1000",
  "payed": "true",
  "payMethod": "swish",
  "products": [{"test": "test", "test2": "test2"}]
    
}


###

// ADD PRODUCT DATA
POST http://localhost:3000/addproduct
Content-Type: application/json

{
  "articleNumber": "12345",
  "name": "bergman",
  "picture": ["hej", "hejsan"],
  "thumbnail": ["hej", "hejsan"]
}



###

// ADD PRODUCT DATA
POST http://localhost:3000/order/65155f1f13ed7ade98e4b28e/update
Content-Type: application/json

{
  "firstName": "JonasZ",
  "lastName": "BergmanZ"
}


